export enum NotificationType {
  // Post related notifications
  POST_LIKE = 'POST_LIKE',
  POST_COMMENT = 'POST_COMMENT',
  FOLLOW = 'FOLLOW',
  UNFOLLOW = 'UNFOLLOW',
  
  // Tribe related notifications
  TRIBE_MEMBERSHIP_REQUEST = 'TRIBE_MEMBERSHIP_REQUEST',
  TRIBE_MEMBERSHIP_ACCEPTED = 'TRIBE_MEMBERSHIP_ACCEPTED',
  TRIBE_MEMBERSHIP_REJECTED = 'TRIBE_MEMBERSHIP_REJECTED',
  TRIBE_MEMBER_REMOVED = 'TRIBE_MEMBER_REMOVED',
  TRIBE_MEMBER_PROMOTED = 'TRIBE_MEMBER_PROMOTED',
  TRIBE_UPDATE = 'TRIBE_UPDATE',
  TRIBE_PROMOTION='TRIBE_PROMOTION',
  // Chat related notifications
  NEW_MESSAGE = 'NEW_MESSAGE',
  
  // System notifications
  SYSTEM = 'SYSTEM'
} 